import os
from maticlib.core.text2sql.loaders import SQLAlchemySchemaLoader
from maticlib.core.text2sql.executors import SQLAlchemyExecutor
from maticlib.core.text2sql.guards import SQLInjectionGuard
from maticlib.core.text2sql.tabular_ingestor import TabularIngestor


def example_tabular_ingestion_and_schema():
    print("--- 1. Tabular Ingestion and Schema Loading ---")

    # 1. Create a dummy CSV file
    dummy_csv = "sales_data.csv"
    with open(dummy_csv, "w", encoding="utf-8") as f:
        f.write("id,product,price\n1,Apple,1.20\n2,Banana,0.80\n")

    # 2. Ingest CSV directly into a SQLite database
    db_path = "sqlite:///example_sales.db"
    ingestor = TabularIngestor(connection_string=db_path)

    try:
        table_name = ingestor.ingest_file(dummy_csv, table_name="sales")
        print(f"Successfully ingested {dummy_csv} into table '{table_name}'.")
    except Exception as e:
        print(f"Ingestion failed (missing pandas?): {e}")
        os.remove(dummy_csv)
        return

    os.remove(dummy_csv)

    # 3. Load the Database Schema using the Schema Loader
    loader = SQLAlchemySchemaLoader()
    schema = loader.load_schema(db_path)

    print("\nExtracted Database Schema DDL for LLM Prompting:")
    print(schema.to_prompt_string())


def example_safe_execution():
    print("\n--- 2. Safe Execution with SQLInjectionGuard ---")
    db_path = "sqlite:///example_sales.db"

    # Setup Guard and Executor
    try:
        guard = SQLInjectionGuard(allowed_dialect="sqlite")
        executor = SQLAlchemyExecutor(connection_string=db_path, read_only=True)
    except Exception as e:
        print(f"Failed to initialize (missing dependencies?): {e}")
        return

    # Scenario A: Valid SELECT query (like one generated by an LLM)
    llm_query = "SELECT product, price FROM sales WHERE price > 1.0"
    print(f"\nEvaluating LLM Query: {llm_query}")

    safe_query = guard.validate_and_format(llm_query)
    print(f"Validated Query: {safe_query}")

    cols, rows = executor.execute(safe_query)
    print(f"Results: {cols}")
    for row in rows:
        print(f"  {row}")

    # Scenario B: Malicious DROP query
    malicious_query = "DROP TABLE sales"
    print(f"\nEvaluating LLM Query: {malicious_query}")
    try:
        guard.validate_and_format(malicious_query)
    except Exception as e:
        print(f"Guard successfully blocked query! Reason: {e}")

    # Cleanup
    if os.path.exists("example_sales.db"):
        os.remove("example_sales.db")


if __name__ == "__main__":
    example_tabular_ingestion_and_schema()
    example_safe_execution()
